version: "3.8"

services:
  authentication-app:
    build:
      context: .
      dockerfile: authentication-app/Dockerfile
    ports:
      - "84:84"
    container_name: authentication-app

  ecommerce-main:
    build:
      context: .
      dockerfile: ecommerce-main/Dockerfile
    ports:
      - "85:85"
    container_name: ecommerce-main